### ISSUE TITLE
As a developer I would like a consistent structure mapping hosts -> roles.

### ISSUE THREAD

**Issue by jinksunk** [jinksunk/ansible-playbooks#9]
* Inventory will group hosts by abstract roles (ie. webserver, vpn server, etc...)
* The jenkins file included in this repository will specify those roles / playbooks that don't have a separate repository that triggers builds.
  * For example, the openvpn server will likely be entirely contained in this repository
  * The webserver, however, will have a separate repository build a build script that moves web content to the correct location

An example inventory file might be:
```
---
all:
  children:
    webservers:
      hosts:
        www.semantiknit.com:
    publicationservers:
      hosts:
        www.semantiknit.com:
    vpnservers:
      hosts:
        www.semantiknit.com:
```

## Acceptance Criteria
When this repository is committed, all ansible groups without a separate repository should be built and deployed (as specified in the jenkinsfile), including (at this time):
* webservers
* publicationservers
* vpnservers
